export const WomanBandstringData = [{
        id : "1" ,
        Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
        price : "$656 -$1181",
        itemsqu : "Item#: EB70875YS" , 
        caratgold : "18k White Gold",
        Link : "/WomanbandsRingColletionpageAllFile" ,
        nameofMetal : "Setting Information",
        itemName   : "Item#" ,
        itemNameofMetal : "MB80366" ,
        sotnetypeofMetal : "Metal",
        GoldCaratofMetal : "18k White Gold" , 
    
},
{
    id : "2" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "3" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "4" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "5" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "6" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "7" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "8" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "9" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "10" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "11" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "12" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "13" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "14" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "15" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},
{
    id : "16" ,
    Img : " https://d3kinlcl20pxwz.cloudfront.net/image-jewelry/MB83160/WHITEGOLD/FM.jpg" ,
    price : "$656 -$1181",
    itemsqu : "Item#: EB70875YS" , 
    caratgold : "18k White Gold",
    Link : "/" ,
    nameofMetal : "Setting Information",
    itemName   : "Item#" ,
    itemNameofMetal : "MB80366" ,
    sotnetypeofMetal : "Metal",
    GoldCaratofMetal : "18k White Gold" , 

},

]